// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6CEAmSTTWPN6ryVpGST7lWtcd3XC-uH4',
    appId: '1:288435076872:web:d29a021e5450cad7c776bd',
    messagingSenderId: '288435076872',
    projectId: 'chichanka-perfume-app',
    authDomain: 'chichanka-perfume-app.firebaseapp.com',
    storageBucket: 'chichanka-perfume-app.firebasestorage.app',
    measurementId: 'G-N33NPCYDH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVj0w3xtIE8unviC4_3Q-EBvs_r82QNx0',
    appId: '1:288435076872:android:ba2b5cadc039c54fc776bd',
    messagingSenderId: '288435076872',
    projectId: 'chichanka-perfume-app',
    storageBucket: 'chichanka-perfume-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6CEAmSTTWPN6ryVpGST7lWtcd3XC-uH4',
    appId: '1:288435076872:web:a8da64b4edc15184c776bd',
    messagingSenderId: '288435076872',
    projectId: 'chichanka-perfume-app',
    authDomain: 'chichanka-perfume-app.firebaseapp.com',
    storageBucket: 'chichanka-perfume-app.firebasestorage.app',
    measurementId: 'G-5KJE7NN4BG',
  );
}



